spring.application.name=creator-backend
spring.datasource.url=jdbc:h2:file:./data/cvdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8081}

gemini.api.key=${OPENROUTER_API_KEY}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
